In [1]:
import numpy as np

In [ ]:
#Read in the data
prior_belief = np.genfromtxt(
    'phone_prior.csv', # filename
    delimiter=',', # csv cells are demarcated with commas
    names=None, # There is no header information in the first row
    dtype=np.float32 # This informs how all data should be interpreted
)
condi_prob = np.genfromtxt(
    'phone_conditional.csv', # filename
    delimiter=',', # csv cells are demarcated with commas
    names=None, # There is no header information in the first row
    dtype=np.float32 # This informs how all data should be interpreted
)
print(f"{prior_belief}\n\n{condi_prob}")

[[0.05 0.1  0.05 0.05]
 [0.05 0.1  0.05 0.05]
 [0.05 0.05 0.1  0.05]
 [0.05 0.05 0.1  0.05]]

[[0.75 0.95 0.75 0.05]
 [0.05 0.75 0.95 0.75]
 [0.01 0.05 0.75 0.95]
 [0.01 0.01 0.05 0.75]]


Let

$OBS$: An event represents the obervation of two bars of signals

$L_{ab}$: An event represents the user is at the location of row a and column b

$
P(L_{ab}|OBS) = \frac{P(OBS|L_{ab})P(L_{ab})}{P(OBS)} = \frac{P(OBS|L_{ab})P(L_{ab})}{\sum_{i = 1}^{4}\sum_{j = 1}^{4}P(OBS|L_{ij})P(L_{ij})}
$

In [8]:
# Compute P(OBS)
p_OBS = 0

for i in range(0, 4):
    for j in range(0, 4):
        p_OBS += prior_belief[i, j] * condi_prob[i, j]

print(f"P(OBS) = {p_OBS}")

P(OBS) = 0.5040000081062317


In [11]:
# Compute P(L_{ab}|OBS)
p = np.empty((4, 4)) # The array to store the updated probability of each location 

for a in range(0, 4):
    for b in range(0, 4):
        p[a, b] = (prior_belief[a, b] * condi_prob[a, b]) / p_OBS

print(p)

[[0.07440476 0.18849206 0.07440476 0.00496032]
 [0.00496032 0.14880952 0.09424603 0.07440476]
 [0.00099206 0.00496032 0.14880952 0.09424603]
 [0.00099206 0.00099206 0.00992064 0.07440476]]
